# Generated by Django 4.2.30 on 2026-09-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplot_app', '0001_initial'),
        ('hardware_app', '0003_deviceid_route_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceid',
            name='device_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='deviceid',
            name='device_name',
            field=models.CharField(default='Bus Device', max_length=255),
        ),
        migrations.AlterField(
            model_name='deviceid',
            name='route_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='routeplot_app.routeinfo'),
        ),
    ]
